--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LuthMC/EasyGamemode
build-by-default: true
branches:
- main
projects:
  EasyGamemode:
    path: ""
    libs:
      - src: LootSpace369/LSFormAPI/LSFormAPI
        version: 1.0.1
        branch: main
...
