--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LuthMC/EasyGamemode
build-by-default: true
branches:
- main
projects:
  EasyGamemode:
    path: ""
    icon: icon.png
    libs:
      - src: Vasync\LSFormAPI\LSFormAPI
        version: ^1.0.2
...
