name: EasyGamemode
main: LuthMC\EasyGamemode\Main
version: 0.0.2
api: 5.0.0
author: LuthMC
description: A simple plugin to change gamemode easily

commands:
  gmc:
    description: Change gamemode to creative
    permission: easygamemode.gmc
  gms:
    description: Change gamemode to survival
    permission: easygamemode.gms
  gma:
    description: Change gamemode to adventure
    permission: easygamemode.gma
  gmsp:
    description: Change gamemode to spectator
    permission: easygamemode.gmsp
  gmui:
    description: Open Gamemode UI
    permission: easygamemode.ui
  easygamemode:
    description: Main command for EasyGamemode
    usage: /easygamemode [help]
    aliases: [eg]
    permission: easygamemode.easygamemode

permissions:
  easygamemode.gmc:
    description: Allow players to use /gmc
    default: op
  easygamemode.gms:
    description: Allow players to use /gms
    default: op
  easygamemode.gma:
    description: Allow players to use /gma
    default: op
  easygamemode.gmsp:
    description: Allow players to use /gmsp
    default: op
  easygamemode.ui:
    description: Allow players to use /gmui
    default: op
  easygamemode.easygamemode:
    description: Allow players to use /easygamemode and /eg
    default: op
