name: EasyGamemode
main: Luthfi\EasyGamemode\Main
version: 1.0.1
api: 5.0.0
author: Luthfi
description: A simple plugin to change gamemode easily

commands:
  gmc:
    description: Change gamemode to creative
    permission: easygamemode.gmc
  gms:
    description: Change gamemode to survival
    permission: easygamemode.gms
  gma:
    description: Change gamemode to adventure
    permission: easygamemode.gma
  gmsp:
    description: Change gamemode to spectator
    permission: easygamemode.gmsp
  easygamemode:
    description: Main command for EasyGamemode
    usage: /easygamemode [help]
    aliases: [eg]
    permission: easygamemode.easygamemode

permissions:
  easygamemode.gmc:
    description: Allows players the use of /gmc
    default: op
  easygamemode.gms:
    description: Allows players the use of /gms
    default: op
  easygamemode.gma:
    description: Allows players the use of /gma
    default: op
  easygamemode.gmsp:
    description: Allows players the use of /gmsp
    default: op
  easygamemode.easygamemode:
    description: Allows players the use of /easygamemode and /eg
    default: op
